version: "3.9"

services:
  krake.api:
    image: krake.api
    container_name: Krake.Api
    build:
      context: .
      dockerfile: src/Krake.Api/Dockerfile
    depends_on:
      krake.database.sql:
        condition: service_started
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Test1234!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/certificates/cert.pfx
    ports:
      - "5000:8080"
      - "5001:8081"

  krake.database.sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Krake.Database.Sql
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=Admin#123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/mssql:/var/opt/mssql/data

  krake.database.sql.seed:
    depends_on: [krake.database.sql]
    build:
      context: database/
      dockerfile: Dockerfile
    image: krake.database.sql.seed
    container_name: Krake.Database.Sql.Seed

  krake.seq:
    image: datalust/seq:latest
    container_name: Krake.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5002:80"
      - "5341:5341"

  krake.redis:
    image: redis:latest
    container_name: Krake.Redis
    restart: always
    ports:
      - "6379:6379"

  # Currently only used for local dev
  # krake.angular:
  #   build:
  #       context: ./krake-angular/.
  #   image: krake.angular
  #   container_name: Krake.Angular
  #   restart: no
  #   ports:
  #     - "5003:80"
