// Docker
#@Krake.Api = https://localhost:5001
// Local
@Krake.Api = https://localhost:5081

### HealthChecks
GET {{Krake.Api}}/health

### Create a new portfolio
POST {{Krake.Api}}/portfolios
Accept: application/json
Content-Type: application/json

{
    "name": "New Portfolio"
}

### List portfolios
GET {{Krake.Api}}/portfolios

### Get portfolio by id
@portfolioId=87c6f6fb-2f21-450e-aeca-46b58cf2df5f
GET {{Krake.Api}}/portfolios/{{portfolioId}}

### Update a portfolio
PUT {{Krake.Api}}/portfolios/{{portfolioId}}
Accept: application/json
Content-Type: application/json

{
    "name": "Updated Portfolio"
}

### Delete a portfolio
DELETE {{Krake.Api}}/portfolios/{{portfolioId}}