name: .NET Docker

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - database/**
      - docs/**
      - python/**

  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Spin up database
        run: docker compose up -d

      - name: Tear down database
        if: always()
        run: docker compose down