name: dotnet-krake-api

on:
  push:
    branches:
      - "main"
    paths:
      - "src/Krake.Api/**"
      - "tests/Krake.Api.Tests.Integration/**"

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Self sign https certificate
        shell: pwsh
        run: |
          cd ./src/Krake.Api/
          dotnet dev-certs https --clean
          mkdir certificates
          cd ./certificates
          dotnet dev-certs https -ep cert.pfx -p ${{ secrets.CERT_PW }}
          dotnet dev-certs https --trust

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Spin up required services
        run: |
          docker compose up -d \
          krake.database.sql \
          krake.redis \
          krake.seq

      - name: Seed main and testing database
        run: |
          docker compose up -d \
          krake.database.sql.migrator \
          krake.database.sql.seed.testing

      - name: Build and perform integration tests
        run: |
          docker build \
          -f ./src/Krake.Api/Dockerfile \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/krake.api:latest \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/krake.api:${{github.run_number}} \
          --network host \
          .

      - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/krake.api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/krake.api:${{github.run_number}}

      - name: Tear down containers
        if: always()
        run: docker compose down
